project_id = "lvdimtiefbjglywokncr"

[functions.ai-content-analysis]
verify_jwt = true

[functions.ai-generate]
verify_jwt = true

[functions.brain-indexer]
verify_jwt = true

[functions.brain-search]
verify_jwt = true

[functions.account-context]
verify_jwt = true

[functions.brain-optimizer]
verify_jwt = true

[functions.content-ideas]
verify_jwt = true

[functions.viral-analyzer]
verify_jwt = true