project_id = "lvdimtiefbjglywokncr"

[functions.ai-content-analysis]
verify_jwt = true

[functions.ai-generate]
verify_jwt = true

[functions.brain-indexer]
verify_jwt = true

[functions.brain-search]
verify_jwt = true