// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvdimtiefbjglywokncr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2ZGltdGllZmJqZ2x5d29rbmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTE5MzcsImV4cCI6MjA3MDg2NzkzN30._cdaYCMd6Y_MAgvTaj7253kUND3-Z3tpwcXOV0YnD_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});